version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.1.0
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=s3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./src/main/config/aws:/etc/localstack/init/ready.d:ro
  db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: file_sharing_application_bd
    volumes:
      - ./src/main/config/db:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
  api:
    container_name: file-sharing-application
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    command: "npm run start"
    depends_on:
      - localstack
      - db
    links:
      - localstack
      - db